version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    hostname: app
    environment:
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_HOST=dl-database
      - DB_PORT=5432
      - DB_NAME=dl-database
      - REDIS_HOST=dl-redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
      - REDIS_DB=0
    ports:
      - "3000:3000"
    networks:
      - dev-network-dl

networks:
  dev-network-dl:
    driver: bridge